module.exports = {
  ava: require('./ava'),
  browser: require('./browser'),
  canonical: require('./canonical'),
  cypress: require('./cypress'),
  flowtype: require('./flowtype'),
  graphql: require('./graphql'),
  jest: require('./jest'),
  jsdoc: require('./jsdoc'),
  json: require('./json'),
  jsxA11y: require('./jsx-a11y'),
  lodash: require('./lodash'),
  mocha: require('./mocha'),
  module: require('./module'),
  next: require('./next'),
  node: require('./node'),
  prettier: require('./prettier'),
  react: require('./react'),
  regexp: require('./regexp'),
  typescript: require('./typescript'),
  vitest: require('./vitest'),
  yaml: require('./yaml'),
  zod: require('./zod'),
};
