module.exports = {
  plugins: [
    '@next/next',
  ],
  rules: {
    '@next/next/google-font-display': 1,
    '@next/next/google-font-preconnect': 1,
    '@next/next/inline-script-id': 2,
    '@next/next/link-passhref': 1,
    '@next/next/next-script-for-ga': 1,
    '@next/next/no-css-tags': 1,
    '@next/next/no-document-import-in-page': 2,
    '@next/next/no-duplicate-head': 2,
    '@next/next/no-head-import-in-document': 2,
    '@next/next/no-html-link-for-pages': 1,
    '@next/next/no-img-element': 1,
    '@next/next/no-page-custom-font': 1,
    '@next/next/no-script-in-document': 2,
    '@next/next/no-script-in-head': 2,
    '@next/next/no-server-import-in-page': 2,
    '@next/next/no-sync-scripts': 1,
    '@next/next/no-title-in-document-head': 1,
    '@next/next/no-typos': 1,
    '@next/next/no-unwanted-polyfillio': 1,
  },
};
